meta_product_name: "Code & Drink - The Game"
meta_title: "Code & Drink - The Game"
meta_description: "Code & Drink is a fun game to play with your friends! Join us to learn to code and have some fun!"
meta_image: "codeanddrink.jpg"
twitter_account: "@lewagonparis"
